"""Recall/QPS measurement path: ann-benchmarks, run inside each engine image.

ann-benchmarks is used unmodified. Rather than letting its own Docker runner
launch containers (which would give us no control over env, cpuset or memory),
the orchestrator launches the container itself and runs `run.py --local` inside
it. Local mode executes the algorithm in-process, so ann-benchmarks still owns
definitions, ground truth, recall computation and result files, while the
orchestrator owns the container's resource limits. No patching of the upstream
project is required.
"""

from __future__ import annotations

import os
import shutil
from typing import Any, Dict, List, Optional

import yaml

from . import docker_ctl
from .config import ResolvedResources, server_args

# Constructor class names, as ann-benchmarks expects them in config.yml.
CONSTRUCTORS = {"mariadb": "MariaDB", "alisql": "AliSQL", "pgvector": "PGVector"}


def annb_results_dir(paths: Dict[str, str], resource_pass: str) -> str:
    """Result tree for one resource pass.

    ann-benchmarks derives its result filenames from the algorithm and its
    parameters, with no notion of a resource pass. Sharing one tree would make
    the tuned pass skip every point the normalized pass already computed — and
    the report would then present normalized numbers as tuned ones. Separate
    trees keep the two passes independent and keep resumption working within
    each.
    """
    path = os.path.join(paths["annb_results"], resource_pass)
    os.makedirs(path, exist_ok=True)
    return path


def render_config(engine: str, profile: Dict[str, Any],
                  resources: Dict[str, Any], resource_pass: str) -> Dict[str, Any]:
    """Build the ann-benchmarks config.yml body for one engine and profile.

    Generated rather than hand-maintained so a profile change cannot leave one
    engine sweeping a different grid from the others — which would look like a
    performance difference and would not be one.
    """
    ann = profile.get("ann", {}) or {}
    m_values = list(ann.get("m_values", [16]))
    query_args = [list(ann.get("ef_search", [10, 40, 160]))]
    extras = (resources.get("extras", {}) or {}) if resource_pass == "tuned" else {}

    run_groups: Dict[str, Any] = {}

    if engine in ("mariadb", "alisql"):
        if engine == "mariadb":
            storage_engines = list(
                extras.get("mariadb_storage_engines")
                or ann.get("mariadb_storage_engines", ["InnoDB"])
            )
        else:
            # VIDX is InnoDB-only; offering anything else would fail at DDL.
            storage_engines = ["InnoDB"]

        for storage in storage_engines:
            run_groups[storage.lower()] = {
                "arg_groups": [{"M": m_values, "engine": storage}],
                "args": {},
                "query_args": query_args,
            }

    elif engine == "pgvector":
        if resource_pass == "tuned" and extras.get("pgvector_ef_construction"):
            ef_constructions = list(extras["pgvector_ef_construction"])
        else:
            # Pinned in the normalized pass: ef_construction is the one build
            # knob MariaDB and AliSQL do not expose, so sweeping it there would
            # hand pgvector a tuning axis the others lack.
            ef_constructions = [int(ann.get("pgvector_ef_construction", 200))]

        for build_mode in ann.get("pgvector_build_modes", ["post"]):
            run_groups[f"{build_mode}_build"] = {
                "arg_groups": [{
                    "M": m_values,
                    "efConstruction": ef_constructions,
                    "build_mode": build_mode,
                }],
                "args": {},
                "query_args": query_args,
            }
    else:
        raise ValueError(f"unknown engine: {engine}")

    return {
        "float": {
            "any": [{
                "base_args": ["@metric"],
                "constructor": CONSTRUCTORS[engine],
                "disabled": False,
                "docker_tag": f"vector-bench/{engine}-bench",
                "module": f"ann_benchmarks.algorithms.{engine}",
                "name": engine,
                "run_groups": run_groups,
            }]
        }
    }


def write_config(work_dir: str, engine: str, body: Dict[str, Any]) -> str:
    """Write the rendered config into the disposable ann-benchmarks working copy."""
    path = os.path.join(work_dir, "ann_benchmarks", "algorithms", engine, "config.yml")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    header = (
        f"# GENERATED by vector-bench for engine '{engine}'. Do not edit.\n"
        f"# Regenerate with: ./run-benchmark.sh render --profile <name>\n"
    )
    with open(path, "w") as fh:
        fh.write(header)
        yaml.safe_dump(body, fh, sort_keys=False, default_flow_style=False)
    return path


def run_engine(engine: str, dataset: str, profile: Dict[str, Any],
               engine_cfg: Dict[str, Any], resolved: ResolvedResources,
               resource_pass: str, paths: Dict[str, str], run_id: str,
               force: bool = False, timeout_s: int = 24 * 3600) -> int:
    """Run the ann-benchmarks sweep for one engine on one dataset."""
    image = engine_cfg.get("image", {}).get("bench", f"vector-bench/{engine}-bench")
    if not docker_ctl.image_exists(image):
        raise docker_ctl.DockerError(
            f"image {image} not found. Build it first:\n"
            f"  ./run-benchmark.sh build --engines {engine}"
        )

    flags = server_args(engine_cfg, resource_pass, resolved)
    container = f"{run_id}-annb-{engine}-{dataset}".replace("_", "-")[:60]

    command = [
        "run.py", "--local",
        "--algorithm", engine,
        "--dataset", dataset,
        "--count", str(profile.get("k", 10)),
        "--runs", str(profile.get("runs", 1)),
        "--parallelism", "1",
    ]
    if profile.get("ann", {}).get("batch"):
        command.append("--batch")
    if force:
        command.append("--force")

    spec = docker_ctl.ContainerSpec(
        name=container,
        image=image,
        # No network needed: the dataset is mounted and the server is in-process.
        network="none",
        cpuset=resolved.server_cpuset,
        memory_bytes=resolved.server_memory_bytes,
        shm_size=resolved.shm_size,
        entrypoint="python3",
        workdir="/home/app",
        env={
            "VB_SERVER_ARGS": " ".join(flags),
            "VB_INSERT_THREADS": str(profile.get("ann", {}).get("insert_threads", 0)),
            "VB_RUN_ID": run_id,
            "VB_RESOURCE_PASS": resource_pass,
            "PYTHONUNBUFFERED": "1",
        },
        volumes=[
            f"{paths['work_annb']}:/home/app:rw",
            f"{paths['datasets']}:/home/app/data:rw",
            f"{annb_results_dir(paths, resource_pass)}:/home/app/results:rw",
        ],
        command=command,
        detach=False,
    )

    print(f"[ann] {engine} / {dataset}: cpuset={resolved.server_cpuset} "
          f"mem={resolved.server_memory_bytes / 1024**3:.1f}GB")
    print(f"[ann] server flags: {' '.join(flags)}")
    return docker_ctl.run_foreground(spec, timeout=timeout_s)


def fix_ownership(path: str, image: str) -> None:
    """Return root-created result files to the invoking user.

    The engines run as root inside their containers, so anything they write to a
    bind mount lands root-owned on the host. Left alone that makes the results
    directory unreadable to the user who started the run.
    """
    uid, gid = os.getuid(), os.getgid()
    if uid == 0:
        return
    spec = docker_ctl.ContainerSpec(
        name=f"vb-chown-{os.getpid()}",
        image=image,
        entrypoint="chown",
        command=["-R", f"{uid}:{gid}", "/target"],
        volumes=[f"{path}:/target:rw"],
        detach=False,
        network="none",
    )
    docker_ctl.run_foreground(spec, timeout=600, stream=False)
