#!/usr/bin/env bash
#
# Entrypoint for the vector-bench Percona Server for MongoDB + mongot image.
#
#   vb-entrypoint server [extra mongod args...]  start mongod and mongot
#   vb-entrypoint client [args...]               open mongosh on the ann database
#   vb-entrypoint <anything else>                exec it verbatim
#
# Two processes and, unavoidably, authentication. Every other engine in this
# framework runs with auth off, because credentials add a round trip to nothing
# that is being measured. mongot does not offer that choice:
#
#   BsonParseException: "syncSource" Exactly one authentication mechanism
#   must be used (x509 or scram)
#
# It refuses to parse a config without SCRAM or x509, so mongod has to run with
# auth enabled and a user mongot can authenticate as. That in turn means a
# keyfile, because a replica set with auth requires internal member auth, and
# it means the benchmark client authenticates too. All of this is set up here
# so the cost is a fixed startup, not something that varies per measurement.
#
# mongot itself takes no configuration on the command line. Its only option is
# --config; everything else is the YAML written below.

set -euo pipefail

DBPATH="${VB_DBPATH:-/var/lib/vbench/db}"
MONGOT_DATA="${VB_MONGOT_DATA:-/var/lib/vbench/mongot}"
RS="${VB_REPLICA_SET:-rs0}"
PORT="${VB_MONGOD_PORT:-27017}"
MONGOT_PORT="${VB_MONGOT_PORT:-27028}"
HEAP_GB="${VB_MONGOT_HEAP_GB:-8}"

USER_NAME="${VB_MONGO_USER:-bench}"
USER_PASS="${VB_MONGO_PASSWORD:-bench}"
MONGOT_USER="mongotUser"
MONGOT_PASS="${VB_MONGOT_PASSWORD:-mongotbench}"

KEYFILE=/var/lib/vbench/keyfile
SECRET=/etc/mongot/secrets/passwordFile
MONGOT_CONF=/etc/mongot/mongot.yml

log() { printf '[vb-mongodb] %s\n' "$*" >&2; }

mongosh_local() { mongosh --quiet --port "$PORT" "$@"; }
mongosh_auth()  { mongosh --quiet --port "$PORT" -u "$USER_NAME" -p "$USER_PASS" \
                          --authenticationDatabase admin "$@"; }

wait_for_mongod() {
  for _ in $(seq 1 180); do
    if mongosh_local --eval 'db.adminCommand({ping:1}).ok' >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  log "mongod did not answer on ${PORT}"; return 1
}

prepare_keyfile() {
  # Internal member authentication. A single-node replica set still needs one
  # once auth is on, and mongod refuses to start if the file is group or
  # world readable.
  [[ -f "$KEYFILE" ]] && return 0
  mkdir -p "$(dirname "$KEYFILE")"
  openssl rand -base64 756 > "$KEYFILE"
  chmod 400 "$KEYFILE"
  chown "$(id -u):$(id -g)" "$KEYFILE" 2>/dev/null || true
}

bootstrap_users() {
  # The localhost exception lets exactly one thing happen on a fresh, empty,
  # auth-enabled deployment: create the first user. rs.initiate() has to come
  # first, and after the first createUser the exception closes, so everything
  # below runs in one ordered pass.
  if mongosh_auth --eval 'db.adminCommand({ping:1}).ok' >/dev/null 2>&1; then
    log "users already provisioned"
    return 0
  fi

  log "initiating single-node replica set ${RS}"
  mongosh_local --eval \
    "rs.initiate({_id:'${RS}',members:[{_id:0,host:'localhost:${PORT}'}]})" >/dev/null

  # PRIMARY, not merely initiated: createUser is a write and fails until the
  # election completes.
  for _ in $(seq 1 60); do
    [[ "$(mongosh_local --eval 'db.hello().isWritablePrimary' 2>/dev/null)" == "true" ]] \
      && break
    sleep 1
  done

  log "creating benchmark user '${USER_NAME}' and '${MONGOT_USER}'"
  mongosh_local --eval "
    db.getSiblingDB('admin').createUser({
      user: '${USER_NAME}', pwd: '${USER_PASS}',
      roles: [{role:'root', db:'admin'}] });
  " >/dev/null

  # searchCoordinator is the role mongot's own default config documents.
  mongosh_auth --eval "
    db.getSiblingDB('admin').createUser({
      user: '${MONGOT_USER}', pwd: '${MONGOT_PASS}',
      roles: [{role:'searchCoordinator', db:'admin'}] });
  " >/dev/null
}

write_mongot_config() {
  # mongot enforces owner-only permissions on the secret and refuses to start
  # otherwise.
  mkdir -p "$(dirname "$SECRET")" "$MONGOT_DATA"
  printf '%s' "$MONGOT_PASS" > "$SECRET"
  chmod 400 "$SECRET"

  cat > "$MONGOT_CONF" <<YML
# GENERATED by vector-bench. mongot takes no command-line configuration beyond
# --config, so every setting the run depends on is written here.
syncSource:
  replicaSet:
    hostAndPort: "localhost:${PORT}"
    scramAuth:
      username: "${MONGOT_USER}"
      passwordFile: "${SECRET}"
      authSource: admin
      tls:
        enabled: false
storage:
  dataPath: "${MONGOT_DATA}"
server:
  grpc:
    address: "localhost:${MONGOT_PORT}"
    tls:
      mode: "disabled"
metrics:
  enabled: false
healthCheck:
  address: "localhost:8080"
logging:
  verbosity: INFO
YML
}

start_mongot() {
  write_mongot_config
  # Heap scales with the number of indexed fields, not the number of vectors:
  # the vectors are served from memory-mapped segments in the filesystem cache,
  # so oversizing this takes memory from the cache that answers queries.
  log "starting mongot on ${MONGOT_PORT} with ${HEAP_GB}g heap"
  mongot --config="$MONGOT_CONF" --jvm-flags "-Xms${HEAP_GB}g -Xmx${HEAP_GB}g" \
      >"${MONGOT_DATA}/mongot.log" 2>&1 &
  echo $! > /tmp/mongot.pid
  wait_for_mongot
}

wait_for_mongot() {
  # mongod answers long before mongot does: the JVM takes fifteen to twenty
  # seconds to reach its health check. A createSearchIndexes issued in that
  # window is accepted, creates a Lucene index, and then sits in PENDING with
  # no initial sync ever queued for it. The ops path never hit this because the
  # orchestrator spends that long starting a separate client container; the ann
  # path runs in-process and got there in three seconds.
  local health="${VB_MONGOT_HEALTH_PORT:-8080}"
  for _ in $(seq 1 120); do
    if (exec 3<>/dev/tcp/127.0.0.1/"$health") 2>/dev/null; then
      exec 3<&- 2>/dev/null || true
      log "mongot health check is answering on ${health}"
      return 0
    fi
    sleep 1
  done
  log "WARNING: mongot did not answer its health check within 120s; "
  log "         search index creation may fail or hang in PENDING"
  return 0
}

start_server() {
  mkdir -p "$DBPATH" "$MONGOT_DATA"
  prepare_keyfile

  local -a args=(
    mongod --dbpath "$DBPATH" --port "$PORT" --bind_ip_all
    --replSet "$RS" --keyFile "$KEYFILE" --auth
  )
  # shellcheck disable=SC2206
  [[ -n "${VB_SERVER_ARGS:-}" ]] && args+=( ${VB_SERVER_ARGS} )
  args+=( "$@" )

  "${args[@]}" &
  local mongod_pid=$!

  wait_for_mongod
  bootstrap_users
  start_mongot

  # mongod is the container's lifetime; if it exits, so does everything.
  wait "$mongod_pid"
}

case "${1:-server}" in
  server) shift; start_server "$@" ;;
  client) shift; exec mongosh --port "$PORT" -u "$USER_NAME" -p "$USER_PASS" \
                              --authenticationDatabase admin \
                              "${VB_DATABASE:-ann}" "$@" ;;
  *)      exec "$@" ;;
esac
